In [1]:
import numpy as np
import random


pop_size = 4  
num_genes = 4  
mutation_prob = 0.1  
num_iterations = 100 


#fitness function
def fitness_func(chromosome):
    """Calculate the fitness of a chromosome"""
    return np.sum(chromosome)

def initialize_population():
    """Initialize the population"""
    population = np.zeros((pop_size, num_genes), dtype=int)
    for i in range(pop_size):
        # Randomly initialize each gene (either 0 or 1)
        population[i] = np.random.randint(2, size=num_genes)
    return population

def selection(population, fitness):
    """ select two parents"""
    
    probabilities = fitness / np.sum(fitness)
    selected_indices = np.random.choice(range(pop_size), size=2, replace=False, p=probabilities)
    return population[selected_indices]


def crossover(parents):
    
    
    crossover_point = np.random.randint(1, num_genes)
    c1 = np.concatenate((parents[0][:crossover_point], parents[1][crossover_point:]))
    c2 = np.concatenate((parents[1][:crossover_point], parents[0][crossover_point:]))
    return c1, c2

def mutation(chromosome):
  
    for i in range(num_genes):
        if np.random.rand() < mutation_prob:
            chromosome[i] = 1 - chromosome[i]
    return chromosome

def replace(population, fitness, children):
   
    worst_indices = np.argsort(fitness)[:2]
    population[worst_indices[0]] = children[0]
    population[worst_indices[1]] = children[1]
    return population


population = initialize_population()
for i in range(num_iterations):
    
    # Calculate fitness of each chromosome in the population
    fitness = np.apply_along_axis(fitness_func, axis=1, arr=population)

    # Select two parents
    parents = selection(population, fitness)

    # Create two children using single-point crossover
    children = crossover(parents)

    # Mutate the children
    children = tuple(map(mutation, children))

    # Calculate the fitness of the two children and apply the goal test
    
    child_fitness = tuple(map(fitness_func, children))
    if np.max(child_fitness) == num_genes:
        print("Solution found in", i, "iterations.")
        break

    # Replace the two least fit individuals with the children
    population = replace(population, fitness, children)

print("Final population:")
print(population)
print("Fitness values:")
print(fitness)


Solution found in 0 iterations.
Final population:
[[0 1 1 1]
 [0 0 0 0]
 [0 0 0 1]
 [1 0 0 0]]
Fitness values:
[3 0 1 1]
